# Generated by Django 2.1.15 on 2022-08-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logowania',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField()),
                ('userName', models.CharField(max_length=64)),
                ('timeIn', models.CharField(max_length=19)),
                ('type', models.CharField(max_length=16)),
                ('prevId', models.IntegerField()),
                ('sessionId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pracownicy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('cardId', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('hasAdmin', models.BooleanField()),
            ],
        ),
    ]
