# Generated by Django 2.1.15 on 2022-10-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logowania',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pracownicy',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
