# Generated by Django 2.1.15 on 2022-08-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logowania',
            name='userid',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pracownicy',
            name='cardId',
            field=models.CharField(max_length=10),
        ),
    ]
